import { ChakraProvider } from "@chakra-ui/react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "./_providers/Providers";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ChakraProvider>
        <body
          style={{
            maxWidth: "100vw",
            maxHeight: "100vh",
            overflow: "hidden",
          }}
        >
          {children}
        </body>
      </ChakraProvider>
    </html>
  );
}
